#pragma once

namespace tse
{
namespace stlticketingcxr
{
enum _STLTicketingCxrElementIdx_
{
  VALIDATINGCXR_CHECK,
  SETTLEMENTPLAN_CHECK,
  DISPLAY_VALIDATINGCXR,
  DISPLAY_INTERLINEAGREEMENT,
  POS,
  ACTUAL,
  HOME,
  PCC,
  SETTLEMENT_PLAN,
  VALIDATING_CXR,
  PARTICIPATING_CXR,
  TICKET_TYPE,
  TICKET_DATE,
  REQUESTED_DIAGNOSTIC,
  BILLINGINFORMATION,
  NUMBER_OF_ELEMENT_NAMES_TKT_CXR
};

enum _STLTicketingCxrAttributeIdx_
{
  COMPANY, // 0
  DUTY,
  LNIATA,
  MULTIHOST,
  PRIMEHOST,
  SINE,
  CITY,
  COUNTRY,
  COUNTRYCODE,
  SETTLEMENTPLAN,
  CARRIER_CODE,
  NUMBER,
  PROVINCE,
  REQUEST_DATE,
  REQUEST_TIME_OF_DAY,
  ACTIONCODE,
  BUSINESS_FUNCTION,
  PARENT_SERVICE_NAME,
  PARENT_TRANSACTION_ID,
  SOURCE_OF_REQUEST,
  USER_BRANCH,
  USER_SET_ADDRESS,
  USER_STATION,
  NUMBER_OF_ATTRIBUTE_NAMES_TKT_CXR
};

extern const char* _STLTicketingCxrElementNames[];
extern const char* _STLTicketingCxrAttributeNames[];
}
}
