#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.env.add_include_paths('include')
s.env.add_isystem_paths('$XERCESC_CPPPATH_')
s.env.add_defines('ATSE_HYBRID')
s.werror = False
s.mslibrary('idopcpp', 'IDOP_CPP_SOURCES')
s.build()
