#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.mslibrary('FaresCommon', 'FARES_COMMON_SOURCES')
s.mslibrary('FaresValidator', 'FARES_VALIDATOR_SOURCES')
s.mslibrary('FaresCollector', 'FARES_COLLECTOR_SOURCES')
s.werror = True
s.build()

