#!/bin/bash

# ensure we are running within the same directory
# where we are located

cd $(dirname $(which ${0}))
. ./env.vars

declare    run1=${1}
declare    run2=${2}
declare    opt1=${3}
declare    cacheName=""
declare    sortmod=""
declare    equals=""
declare    num=""
declare    junk=""
declare    user=$(whoami)
declare -i counter=0
declare -i remainder=0
declare -i prevNum=0
declare -i currNum=0
declare -i tempDiff=0
declare -i idx=0

grep "keys in" ${APPDIR}/compkeys${run1}.txt | awk '{print $1,"a =",$4}' | sed 's/[][]//'g > /tmp/${user}.compcache.1.tmp
grep "keys in" ${APPDIR}/compkeys${run2}.txt | awk '{print $1,"b =",$4}' | sed 's/[][]//'g > /tmp/${user}.compcache.2.tmp

echo ""
diff /tmp/${user}.compcache.1.tmp /tmp/${user}.compcache.2.tmp | grep '[<>] .*' | awk -F'[<>]' '{print $2}' | sort | \
while read cacheName sortmod equals num junk ; do
  counter=$(expr ${counter} + 1)
  remainder=$(expr ${counter} % 2)
  if [ ${remainder} -eq 0 ] ; then
    currNum=${num}
    tempDiff=$(expr ${currNum} - ${prevNum})
    if [ ${tempDiff} -gt 0 ] ; then
      say "$(printf "%-30s  %8d  /  %8d\n" ${cacheName} ${prevNum} ${currNum})"
    elif [ "${opt1}" = "-all" ] ; then
      say "$(printf "%-30s  %8d  /  %8d" ${cacheName} ${prevNum} ${currNum})"
      echo "  -  No change."
    fi
    prevNum=0
    currNum=0
  else
    prevNum=${num}
  fi
done

rm /tmp/${user}.compcache.1.tmp
rm /tmp/${user}.compcache.2.tmp
