#!/bin/bash

# ensure we are running within the same directory
# from which we are located

script=$(which ${0})
script_dir=$(dirname ${script})

cd ${script_dir}
if [ $? -ne 0 ] ; then exit 1 ; fi

. ./env.vars
if [ $? -ne 0 ] ; then exit 1 ; fi

cd ${APPDIR}
if [ $? -ne 0 ] ; then exit 1 ; fi

cd cfg.${SYSTYPE}
if [ $? -ne 0 ] ; then exit 1 ; fi

if [ -e dbaccess.ini ] ; then
  if [ ! -e dbaccess.ini.original ] ; then
     mv dbaccess.ini dbaccess.ini.original
     if [ $? -ne 0 ] ; then exit 1  ; fi
  fi
fi

cp ${script_dir}/dbaccess.ini.${ENV}.${APP} dbaccess.ini 
if [ $? -ne 0 ] ; then exit 1 ; fi

