#!/bin/bash

# ensure we are running within the same directory
# from which we are running
cd $(dirname $(which ${0}))
. ./env.vars

declare -i MILLIS_RESULT=0
declare    TIME_RESULT=""

function millis_to_time
{
  local -i m=${1}

  local -i mmm=$(expr ${m} % 1000)
  local -i ss=$(expr ${m} / 1000)

  local -i mm=$(expr ${ss} / 60)
  ss=$(expr ${ss} % 60)

  local -i hh=$(expr ${mm} / 60)
  mm=$(expr ${mm} % 60)

  TIME_RESULT=$(printf "tseserver startup time (HH:MM:SS,ms): %2.2d:%2.2d:%2.2d,%3.3d" ${hh} ${mm} ${ss} ${mmm})
}

function time_to_millis
{
  local t=${1}

  local -i hh=$(echo ${t} | awk -F: '{print $1}' | sed 's/0*//')
  local -i mm=$(echo ${t} | awk -F: '{print $2}' | sed 's/0*//')
  local ss_mmm=$(echo ${t} | awk -F: '{print $3}')
  local -i ss=$(echo ${ss_mmm} | awk -F, '{print $1}' | sed 's/0*//')
  local -i mmm=$(echo ${ss_mmm} | awk -F, '{print $2}' | sed 's/0*//')

  local -i temp=0

  MILLIS_RESULT=${mmm}

  temp=$(expr ${ss} * 1000)
  MILLIS_RESULT=$(expr ${MILLIS_RESULT} + ${temp})

  temp=$(expr ${mm} * 60 * 1000)
  MILLIS_RESULT=$(expr ${MILLIS_RESULT} + ${temp})

  temp=$(expr ${hh} * 60 * 60 * 1000)
  MILLIS_RESULT=$(expr ${MILLIS_RESULT} + ${temp})
}

set -o noglob

declare LOGFILE=${APPDIR}/tseserver.log

if [ ! -e "${LOGFILE}" ] ; then
  say "SORRY!  File [${LOGFILE}] not found!"
  exit 1
fi
  
declare START_LINE=$(grep "Config initialized" ${LOGFILE} | tail -1)
if [ -z "${START_LINE}" ] ; then
  say "SORRY!  No start line found in [${LOGFILE}]!"
  exit 1
fi
    
declare READY_LINE=$(grep "TseServer is running" ${LOGFILE} | tail -1)
if [ -z "${READY_LINE}" ] ; then
  say "SORRY!  No ready line found in [${LOGFILE}]!"
  exit 1
fi

declare START_TIME=$(echo ${START_LINE} | awk '{print $2}')
declare READY_TIME=$(echo ${READY_LINE} | awk '{print $2}')

time_to_millis ${START_TIME}
declare -i START_MILLIS=${MILLIS_RESULT}

time_to_millis ${READY_TIME}
declare -i READY_MILLIS=${MILLIS_RESULT}

declare -i DIFF=0

if [ ${READY_MILLIS} -gt ${START_MILLIS} ] ; then
  DIFF=$(expr ${READY_MILLIS} - ${START_MILLIS})
else
  DIFF=$(expr ${START_MILLIS} - ${READY_MILLIS})
fi
millis_to_time ${DIFF}

say "${TIME_RESULT}"

set +o noglob

