#!/bin/sh
#-----------------------------------------------------------------------------
# Kill process by name
#-----------------------------------------------------------------------------
function kn()
{
   if [ $# -eq 0 ] ; then

      echo "USAGE: $0 <string>"

   else

      if [ $# -eq 2 ] ; then
         MYSIG=$(echo "$2" | tr "[:lower:]" "[:upper:]")
      else
         MYSIG="TERM"
      fi

      TOTAL_FOUND=0
      TOTAL_KILLED=0
      PROCNUM=`ps -fu ${LOGNAME} | grep $1 | grep -v grep | awk '{print $2}'`
      for PID in ${PROCNUM} ; do
         TOTAL_FOUND=`expr $TOTAL_FOUND + 1`
         kill -${MYSIG} ${PID}

         # Some processes may take a little time to die
         sleep 1

         # Did the process die?
         PSLINES=`ps -p ${PID} | wc -l`
         if [ ${PSLINES} -eq 1 ] ; then
            echo "Killed ${PID}."
            TOTAL_KILLED=`expr $TOTAL_KILLED + 1`
         else
            echo "ERROR: Could not kill ${PID}.  Try using a different signal."
         fi
      done

      if [ ${TOTAL_FOUND} -eq 0 ] ; then
         echo "SORRY! No process found with '$1' in the description."
      else
         echo "Killed ${TOTAL_KILLED} processes with '$1' in the description."
      fi

   fi
}

kn $*
