#!/bin/sh

# ensure we are running within the same directory
# from which we are running
cd $(dirname $(which ${0}))
. ./env.vars

THE_CACHE="$1"

if [ -z "${THE_CACHE}" ] ; then
  exit 1
fi

echo ""
echo "Invalidating a key in cache [${THE_CACHE}]"

echo "Getting a key"
THE_KEY=$(./cachetest.sh -cache ${THE_CACHE} -app ${APP} -host ${HOST} -port ${PORT} -cmd memkeys | tail -2 | head -1 | awk '{print $2}')

echo "Invalidating key [${THE_KEY}]"
./cachetest.sh -cache ${THE_CACHE} -app ${APP} -host ${HOST} -port ${PORT} -cmd inval ${THE_KEY}

