#!/bin/bash

# ensure we are running within the same directory
# from which we are running
cd $(dirname $(which ${0}))

. ./env.vars

echo "Waiting for LDC action queue to subside..."
PREV_NUM="0"
while [ true  ] ; do
  LINE=$(grep "all queues" ${APPDIR}/tseserver.log | tail -1)
  if [ -n "$LINE" ] ; then
    NUM=$(echo $LINE | awk -F'[][]' '{print $2}')
    if [ "${NUM}" != "${PREV_NUM}" ] ; then
      PREV_NUM=$NUM
    fi
    if [ "${NUM}" = "0" ] ; then 
      break
    fi
  fi
  sleep 3
done

echo "LDC action queue has subsided."

