#!/bin/bash

# ensure we are running within the same directory
# from which we are running
cd $(dirname $(which ${0}))

. ./env.vars

cd ${APPDIR}

app_stat=""
grep_result=""

while [ -z "${grep_result}" ] ; do
  app_stat=$(./appstat.sh)
  grep_result=$(echo ${app_stat} | grep MIA)
done

echo ${app_stat}
