#!/usr/bin/env python

import os

Import('env')

s = env.scout()

libTaxTestUtilsPath = os.path.join(s.env.absroot, s.env.builddir,
                                   'testroot/bld/Taxes/AtpcoTaxes')
s.env.add_ld_library_paths(libTaxTestUtilsPath)

s.runtests()
s.build()