FILE_LOADER_SOURCES := \
    FileLoader.cpp \
    BFCacheUpdate.cpp \
    GZStream.cpp \
    TextFileLoader.cpp \
    MarketRoutingLoader.cpp \
    MarketRoutingSinglesLoader.cpp \
    MarketRoutingDoublesLoader.cpp \
    MarketRoutingCacheUpdater.cpp \
    BFUtils.cpp \
    FileLoaderBase.cpp \
    FileLoaderExtract.cpp \
    FareLoaderFactory.cpp
