#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.werror = True
s.mslibrary('AddonConstruction', 'ADDON_CONSTRUCTION_SOURCES')
s.build()

