#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.mslibrary('ServiceFees', 'SERVICEFEES_SOURCES')
s.werror = True
s.build()
