#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.mslibrary('TicketingCxrDisplayService', 'TICKETING_CXR_DISP_SOURCES')
s.werror = True
s.build()

