#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.scout()
s.env.add_include_paths('$XERCESC_CPPPATH_')
s.tests(blacklist=['test/DSSClientTest.cpp'])
s.build()

