#!/bin/bash

# -p            - do not run the browser (but still print the URL)
# -nokey        - do not require URL key
# -port <PORT>  - use <PORT> port instead of a random one
# -repo <REPO>  - do not run ClearCase commands, use <REPO> directory as a ATSEv2 repository

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#cd /vobs/atseintl/Tools/releasenotes
cd $DIR/../Tools/releasenotes
/opt/jdk1.7.0_01/bin/java -jar $DIR/../Tools/releasenotes/RN.jar -p -repo $DIR/../ $@ | grep -v DEBUG
