#!/bin/bash

# -p            - do not run the browser (but still print the URL)
# -nokey        - do not require URL key
# -port <PORT>  - use <PORT> port instead of a random one
# -repo <REPO>  - do not run ClearCase commands, use <REPO> directory as a ATSEv2 repository


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/../Tools/releasenotes

$JAVA_HOME/bin/java -jar $SCRIPT_DIR/../Tools/releasenotes/target/rnt-1.0-SNAPSHOT-jar-with-dependencies.jar -p -gitrepo $SCRIPT_DIR/../ $@ | grep -v DEBUG
