#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.env.add_isystem_paths('$XERCESC_CPPPATH_', '$ASAP_CPPPATH_', '$ASAPWRAPPER_CPPPATH_')
s.mslibrary('Common', 'COMMON_SOURCES')
s.werror = True
s.build()
