#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.werror = True
s.mslibrary('CacheNotifyManager', 'CACHE_NOTIFY_MANAGER_SOURCES')
s.mslibrary('DiskCacheManager', 'DISKCACHE_NOTIFY_MANAGER_SOURCES')
s.mslibrary('ServerSocketManager', 'SERVER_SOCKET_MANAGER_SOURCES')
s.build()
