#!/usr/bin/env python

# Author: Piotr Bartosik (piotr.bartosik@sabre.com)
# Copyright Sabre 2013

Import('env')

s = env.msscout()
s.env.add_defines('_GNU_SOURCE', 'USE_PTHREADS', 'USE_NO_SPINLOCKS')
s.werror = False
if env['NULL_ALLOCATOR_']:
    s.mslibrary('Allocator', 'NULL_ALLOCATOR_SOURCES')
else:
    s.mslibrary('Allocator', 'ALLOCATOR_SOURCES')
s.build()
