#!/bin/bash

# primary extractor host
PRIMARY_HOST=$1
if [ "$PRIMARY_HOST" == "" ]; then
    logger -t CVGALERT 'No primary extractor host passed. Please check cron.'
    echo "["`date`"] No primary extractor host passed. Please check cron."
    exit 1
fi

# check the existence of previous extractor process
EXTRACTORS=`ps --no-headers axo pid,ppid,cmd | grep binderdatacopy.sh | grep -v grep | grep -v $$ | grep -v $PPID`
echo $EXTRACTORS
if [ "$EXTRACTORS" != "" ]; then
    logger -t CVGALERT 'Extractor process found previous extractor instance running (probably hang). Please check.'
    echo "["`date`"] Extractor process found previous extractor instance running (probably hang). Please check."
    exit 1
fi

HOSTNAME=`hostname`
DATE=`date`

TFILE=$(mktemp)
echo Message generated by binderdatacopy.sh script on $HOSTNAME server > $TFILE
echo " " >> $TFILE
echo RSYNC output: >> $TFILE 
echo " " >> $TFILE
echo ------------------------------------------------------------ >> $TFILE
mkdir -p /opt/atseintl/esv/data/binder
rsync -avz -t --delete --rsh="ssh -o StrictHostKeyChecking=no" $PRIMARY_HOST://sacm/data/binder-esv/ftp/pub/ /opt/atseintl/esv/data/binder >> $TFILE 2>&1
RET=$?
echo ------------------------------------------------------------ >> $TFILE

if [ "$RET" -ne "0" ] ; then
    echo " " >> $TFILE
    echo Binder data server: $PRIMARY_HOST >> $TFILE
    echo Shopping server: $HOSTNAME >> $TFILE
    echo Date: $DATE >> $TFILE
    echo RSYNC command return code: $RET >> $TFILE
    logger -t CVGALERT "RSYNC command return code: $RET"
    EMAIL="AirContentSupportInfo@sabre.com ATSEv2SystemOwners@sabre.com"
    SUBJECT="Binder data copy failed on $HOSTNAME server"
    mail -s "$SUBJECT" "$EMAIL" < $TFILE
fi
rm $TFILE
